export const responseMessage = {
    appResponse: {
        corsError: 'Access denied by CORS',
    },
    passportResponse: {
        accessTokenMissingError: 'Access token missing in header',
    },
    authControllerResponse: {
        loginSuccess: 'User login successfully, ',
        signUpSuccess: 'User signUp successfully',
        verifySuccess: 'Email verified successfully',
        userUpdateSuccess: 'User updated successfully',
        savedBook: 'Saved to My favorite',
        unSavedBook: 'Removed from My Favorite',
        markAsCompletedBook: 'Book mark as completed',
        userAlreadyExistError: 'User already exists',
        userAlreadyVerifiedError: 'User already verified',
        getUserSuccess: 'User fetched successfully',
        getUsersSuccess: 'users fetched successfully',
        getUserError: 'User does not exist',
        getReferralUserError: 'Referral User does not exist',
        userNotAuthorizationError: 'Incorrect credentials or wrong password',
        missingSocialAccountError: '💬 Your account is not registered with us, please do signup with social media account.',
        missingEmailOrPasswordError: 'Email or password is missing',
        missingEmailError: 'Email is required',
        missingAppleEmailError: 'Go to iCloud > Password and Security > App using apple ID > Stop using apple ID.',
        emailAlreadyUsedError: 'Email already used',
        missingoAuthKeyError: 'Client id or provider missing',
        missingEmailAuthError: 'First enable or add your email auth',
        userNotActivatedError: 'User not activated',
        userInvalidPasswordError: 'Password is incorrect',
        userSamePasswordError: 'New password is same as old. Please choose a different one.',
        invalidCodeError: 'Invalid or missing code',
        codeExpiredError: 'Code has been expired, please request new code',
        passwordUpdateSuccess: 'Password has been changed successfully 🚀',
        deleteUserSuccess: 'Account Deleted, All data associated with your account has been deleted permanently.',
        userLogoutSuccess: 'User logout successfully',
        createUserFailed: 'Failed to create user',
        verifyEmailRequest: 'Please check your email and activate your account',
        chnagePasswordRequest: 'Please check your email and finish verification step for new password.',
        blessFriendSuccess: 'User Invited successfully, we\'ve sent your user details on your email',
        blessFriendSubscriptionError: 'Bless friend subscription details missing or not found',
        sentVerifyEmailFailure: 'Failed to send verification email',
        verifyEmailSuccess: 'verification email already sent, in case not received then please click resend verification email',
        sentSubscriptionEmailFilure: 'Subscription plan details were not sent to your email.',
        missingSectionParams: 'Missing section params',
        addShareImage: 'Share image uploaded successfully',
        encodeImageSuccess: 'Image text generated successfully',
        submitQueryError: 'Your message failed to send. Please try again later or contact administrator in another way.',
        paymentStatusPending: 'Payment status is pending, please contact administrator',
        submitQuerySuccess: 'Your message was sent successfully. Thanks!',
        bookRatingSuccess: 'Thanks for rating this summary! 🙂',
        userAuthorisedAsAdmin: 'User is authorized as admin. Please use another email.',
        kindleEmailNotExistError: 'You need to add your Kindle email first. Please click here.',
        emailAuthEnabledSuccess: 'Your email auth enabled',
        emailAuthExist: 'Your email auth already enabled',
        socialLinkError: 'User is authorized as admin. Please use another email.',
        invalidCodeOrTokenError: 'Invalid code or token provided',
        invalidOtpError: 'Incorrect OTP',
        invalidDateError:'Start date should less or equal to end date',
        inValidEmailError:'Please add valid email address',
        noUserFound:'No users found'
    },
    adminControllerResponse: {
        addUserSuccess: 'User added successfully',
        createAdminSuccess: 'Admin added successfully',
        AdminExistError: 'Admin already exists and is verified.',
        createAdminFailure: 'Failed to add admin',
        updateAdminSuccess: 'Admin updated successfully',
        deleteAdminSuccess: 'Admin deleted successfully',
        fetchAdminSuccess: 'Admin details fetched successfully',
        getAdminFailure: 'Admin does not exist',
        sendVerificationEmailSuccess: 'Verification email sent successfully',
        sendCodeFailure: 'Failed to send code',
        verifyCodeSuccess: 'The code was already sent to your email when you signed up. Please verify with the code.',
        forgotPassowrdFailure: 'Your request was not completed. Please try again.',
        updateCodeFailure: 'Failed to proceed verification code',
        codeVerificationFailure: 'Invalid code provided',
        failedToSendPassword: 'Failed to send password on email',
        sentEmailFailure: 'The email did not send. Please try again.',
        forgotPassowrdSuccess: 'Password updated successfully',
        passwordMissingError: 'Password is missing',
        notificationSuccess: 'Notification sent successfully'
    },
    subscriptionsControllerResponse: {
        createSubscriptionSuccess: 'Subscription added successfully',
        createPaymentSheetSuccess: 'Payment sheet created successfully',
        updateSubscriptionSuccess: 'Subscription updated successfully',
        deleteSubscriptionSuccess: 'Subscription deleted successfully',
        fetchSubscriptionSuccess: 'Subscription details fetched successfully',
        fetchSubscriptionsSuccess: 'Subscriptions list fetched successfully',
        createSubscriptionFailure: 'Subscription already added',
        getSubscriptionFailure: 'Failed to fetch subscription details',
        subscriptionIsInUsedError: 'Subscription plan is active in user account',
        subscriptionStatusInActive: 'Subscription status is not active, Please contact administrator',
        planCreateError: 'Failed to create plan',
        planFetchError: 'Failed to fetch plan details',
        planDeleteError: 'Failed to delete plan',
    },
    bookCategoryControllerResponse: {
        createBookCategorySuccess: 'Book category added successfully',
        updateBookCategorySuccess: 'Book category updated successfully',
        deleteBookCategorySuccess: 'Book category deleted successfully',
        fetchBookCategorySuccess: 'Book category details fetched successfully',
        fetchBookCategoriesSuccess: 'Book categories list fetched successfully',
        createBookCategoryFailure: 'Book category already added',
        getBookCategoryFailure: 'Failed to fetch book category details'
    },
    bookSummaryControllerResponse: {
        createBookSummarySuccess: 'Book summary added successfully',
        updateBookSummarySuccess: 'Book summary updated successfully',
        deleteBookSummarySuccess: 'Book summary deleted successfully',
        fetchBookSummarySuccess: 'Book summary details fetched successfully',
        chapterNotExist: 'The summary does not include this takeaway.',
        fetchBookSummariesSuccess: 'Book summary list fetched successfully',
        createBookSummaryFailure: 'Book summary already added',
        getBookSummaryFailure: 'Failed to fetch book summary details',
        trialPlanLimitError: 'You have exceeded your daily limit. Please activate a plan to access unlimited books summaries.',
        planExpiredError: 'Your plan expired, please activate plan for access unlimited books summaries',
        getBookSummaryDocFailure: 'Book reading file missing',
        recommendedBookError: 'This summary is locked because it already exists in your recommended list.',
        sendBookToKindleSuccess: 'The summary was successfully sent to your Kindle.',
        sendBookToKindleEmailFailure: 'The summary was not sent to your Kindle email.',
        getBookRatingsSuccess: 'Book ratings fetched successfully'
    },
    dashboardControllerResponse: {
        getDashboardSuccess: 'Dashboard details fetched successfully'
    },
    authorControllerResponse: {
        createAuthorSuccess: 'Author added successfully',
        updateAuthorSuccess: 'Author updated successfully',
        deleteAuthorSuccess: 'Author deleted successfully',
        fetchAuthorSuccess: 'Author details fetched successfully',
        fetchAuthorsSuccess: 'Authors list fetched successfully',
        createAuthorFailure: 'Author already added',
        getAuthorFailure: 'Failed to fetch author details',
        authorHaveBooksError: 'First remove the summary from author profile.',
    },
    expertCuratedControllerResponse: {
        createExpertCuratedSuccess: 'Expert curated added successfully',
        updateExpertCuratedSuccess: 'Expert curated updated successfully',
        deleteExpertCuratedSuccess: 'Expert curated deleted successfully',
        fetchExpertCuratedSuccess: 'Expert curated details fetched successfully',
        fetchAllExpertCuratedSuccess: 'Expert curated list fetched successfully',
        createExpertCuratedFailure: 'Expert curated already added',
        getExpertCuratedFailure: 'Failed to fetch Expert curated details'
    },
    recommendedBookControllerResponse: {
        createRecommendedBookSuccess: 'Recommended book added successfully',
        createRecommendedBookFailure: 'Recommended book already added',
        updateRecommendedBookSuccess: 'Recommended book updated successfully',
        deleteRecommendedBookSuccess: 'Recommended book deleted successfully',
        fetchRecommendedBookSuccess: 'Recommended book details fetched successfully',
        fetchRecommendedBooksSuccess: 'Recommended books list fetched successfully',
        getRecommendedBookFailure: 'Failed to fetch recommended book details'
    },
    testimonialControllerResponse: {
        createTestimonialSuccess: 'Testimonial added successfully',
        updateTestimonialSuccess: 'Testimonial updated successfully',
        deleteTestimonialSuccess: 'Testimonial deleted successfully',
        fetchTestimonialSuccess: 'Testimonial details fetched successfully',
        fetchTestimonialsSuccess: 'Testimonials list fetched successfully',
        createTestimonialFailure: 'Testimonial already added',
        getTestimonialFailure: 'Failed to fetch testimonial details'
    },
    shareImageControllerResponse: {
        createShareImageSuccess: 'Share image added successfully',
        updateShareImageSuccess: 'Share image updated successfully',
        deleteShareImageSuccess: 'Share image deleted successfully',
        fetchShareImageSuccess: 'Share image details fetched successfully',
        fetchShareImagesSuccess: 'Share images list fetched successfully',
        createShareImageFailure: 'Failed to create share image image',
        shareImageExistError: 'Share image already added',
        getShareImageFailure: 'Failed to fetch share image details'
    },
    readsOfDayControllerResponse: {
        createReadOfDaySuccess: 'Read of the Day added successfully.',
        updateReadOfDaySuccess: 'Read of day updated successfully',
        deleteReadOfDaySuccess: 'Read of day deleted successfully',
        fetchReadOfDaySuccess: 'Read of day details fetched successfully',
        fetchReadsOfDaySuccess: 'Reads of day list fetched successfully',
        createReadOfDayFailure: 'Read of day already added',
        getReadOfDayFailure: 'Failed to fetch Read of day details'
    },
    smallGroupControllerResponse: {
        createSmallGroupSuccess: 'Small group added successfully',
        updateSmallGroupSuccess: 'Small group updated successfully',
        deleteSmallGroupSuccess: 'Small group deleted successfully',
        fetchSmallGroupSuccess: 'Small group details fetched successfully',
        fetchSmallGroupsSuccess: 'Small groups list fetched successfully',
        createSmallGroupFailure: 'Failed to create Small group image',
        smallGroupExistError: 'Small group already added',
        getSmallGroupFailure: 'Failed to fetch small group details'
    },
    highLightsControllerResponse: {
        createHighLightSuccess: 'High light added successfully',
        updateHighLightSuccess: 'Highlight updated successfully.',
        deleteHighLightSuccess: 'High light deleted successfully',
        fetchHighLightsSuccess: 'High lights list fetched successfully',
        invalidHighLightColor: 'Color value should be HEX',
        getHighLightFailure: 'Failed to fetch High light details',
        invalidStartIndexError: 'Start index should be less then end index.'
    },
    cmsControllerResponse: {
        createCmsSuccess: 'Cms added successfully',
        updateCmsSuccess: 'Cms updated successfully',
        deleteCmsSuccess: 'Cms deleted successfully',
        fetchCmsSuccess: 'Cms details fetched successfully',
        fetchAllCmsSuccess: 'All cms list fetched successfully',
        createCmsFailure: 'Cms already added',
        getCmsFailure: 'Failed to fetch cms details',
    },
    FaqControllerResponse: {
        createFaqSuccess: 'Faq added successfully',
        updateFaqSuccess: 'Faq updated successfully',
        deleteFaqSuccess: 'Faq deleted successfully',
        fetchFaqSuccess: 'Faq details fetched successfully',
        fetchAllFaqSuccess: 'All faqs list fetched successfully',
        createFaqFailure: 'Faq already added',
        getFaqFailure: 'Failed to fetch faq details',
    },
    emailTemplateControllerResponse: {
        createEmailTemplateSuccess: 'Email template added successfully',
        updateEmailTemplateSuccess: 'Email template updated successfully',
        deleteEmailTemplateSuccess: 'Email template deleted successfully',
        fetchEmailTemplateSuccess: 'Email template details fetched successfully',
        fetchAllEmailTemplatesSuccess: 'All email templates list fetched successfully',
        createEmailTemplateFailure: 'Email template already added',
        getEmailTemplateFailure: 'Failed to fetch email template details',
    },
    settingControllerResponse: {
        updateSettingSuccess: 'Setting saved successfully',
        fetchSettingSuccess: 'Setting details fetched successfully',
        getSettingFailure: 'Failed to fetch setting details',
    },
    notificationsControllerResponse: {
        createNotificationSuccess: 'Notification created successfully',
        updateNotificationSuccess: 'Notification updated successfully',
        deleteNotificationSuccess: 'Notification deleted successfully',
        getNotificationFailure: 'Failed to fetch notification details',
        fetchNotificationSuccess: 'Notification details fetched successfully',
    },
    transactionsControllerResponse: {
        getTransactionsSuccess: 'Transactions listed successfully',
    },
    handoutsControllerResponse: {
        updateHandoutSuccess: 'Handout updated successfully'
    },
    couponsControllerResponse: {
        couponCreateError: 'Failed to create coupon',
        createCouponSuccess: 'Coupon created successfully',
        getCouponFailure: 'Coupon does not exist',
        fetchCouponSuccess: 'Coupon details fetched successfully',
        fetchCouponsSuccess: 'Coupons list fetched successfully',
        deleteCouponSuccess: 'Coupon removed successfully',
        invalidCoupon: 'Coupon is not valid'
    }
}
